version: 2
updates:

- package-ecosystem: npm
  directory: "/angular/plugins-example"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/components/lifecycle"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/directives/app-attach-directive"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/plugins-core"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/components/component-providers"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/components/component-queries"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/components/component-host"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/components/basic-components"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/app-settings"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/app-i18n"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/plugins"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/pipes/standard-pipes"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/pipes/pure-impure"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/pipes/custom-pipes"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/ng-docker"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/events"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/directives/structural-directives"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/directives/directive-example"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/directives/attribute-directives"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/directives/app-upload-directive"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/angular/dependency-injection"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"

- package-ecosystem: npm
  directory: "/angular/components/dynamic-content"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "@angular/*"
      - dependency-name: "@angular-devkit/*"
      - dependency-name: "@types/*"
      - dependency-name: "typescript"
